version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: task_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
## Backend (fastapi container)

  web: 
    build: .
    container_name: fastapi_tasks_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

   ##Docker Volume     
volumes:
  postgres_data: